export const data = [
  {
    key: "1",
    name: "John Brown11111111",
    age: 32,
    address: "New York No. 1 Lake Park",
  },
  {
    key: "2",
    name: "Jim Green",
    age: 42,
    address: "London No. 1 Lake Park",
  },
  {
    key: "3",
    name: "Joe Black",
    age: 32,
    address: "Sidney No. 1 Lake Park",
  },
  {
    key: "4",
    name: "John Brown",
    age: 32,
    address: "New York No. 1 Lake Park",
  },
  {
    key: "5",
    name: "Jim Green",
    age: 42,
    address: "London No. 1 Lake Park",
  },
  {
    key: "6",
    name: "Joe Black",
    age: 32,
    address: "Sidney No. 1 Lake Park",
  },
  // {
  //   key: "7",
  //   name: "Joe Black7",
  //   age: 32,
  //   address: "Sidney No. 1 Lake Park",
  // },
  // {
  //   key: '8',
  //   name: 'Joe Black8',
  //   age: 32,
  //   address: 'Sidney No. 1 Lake Park',
  // },
  // {
  //   key: '9',
  //   name: 'Joe Black9',
  //   age: 32,
  //   address: 'Sidney No. 1 Lake Park',
  // },
  // {
  //   key: '10',
  //   name: 'Joe Black10',
  //   age: 32,
  //   address: 'Sidney No. 1 Lake Park',
  // },
  // {
  //   key: '11',
  //   name: 'Joe Black11',
  //   age: 32,
  //   address: 'Sidney No. 1 Lake Park',
  // },
  // {
  //   key: '12',
  //   name: 'Joe Black12',
  //   age: 32,
  //   address: 'Sidney No. 1 Lake Park',
  // },
  // {
  //   key: '13',
  //   name: 'Joe Black13',
  //   age: 32,
  //   address: 'Sidney No. 1 Lake Park',
  // },
];